## Multiple Linear Regression using Sklearn

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

## Import Data

In [11]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

## Declare Variables

In [12]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

## Train

In [13]:
reg = LinearRegression()

In [14]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [16]:
reg.intercept_

0.29603261264909486

## R squared

In [17]:
reg.score(x,y)

0.4066811952814285

### Formula for Adjusted R^2
R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [18]:
x.shape

(84, 2)

In [19]:
r2 = reg.score(x,y)

n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1 - (1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

## Feature Selection

In [20]:
from sklearn.feature_selection import f_regression

##### f_regression returns, f-statistic and p values, 1st array is f-stat and 2nd is p-value

In [21]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [22]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [23]:
p_values.round(3)

array([0.   , 0.676])

##### p-value should not be greater thsn 0.05 to be on a safer side, taking 95% confidence interval, and if it's bigger we can reject that feature, as here we will reject 'Rand 1,2,3'

## Summary Table

In [24]:
reg_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [25]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

## Standardization

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()

In [28]:
scaler.fit(x)

C:\Users\risha\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
x_scaled = scaler.transform(x)
x_scaled

C:\Users\risha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

## Train with Standardized data and get summar table

In [37]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [38]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [39]:
reg.intercept_

3.330238095238095

In [42]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns = ['Features'])
reg_summary['Weights'] = reg.intercept_,reg.coef_[0], reg.coef_[1]
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

## Making predictions based on Standardized Data(weights)

In [43]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [44]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

C:\Users\risha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [46]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

## If we remove Rand 1,2,3 , then

In [48]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [50]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

##### We can see that removing Rand 1,2,3 doesn't make much difference, as we previously also knew this by looking at the p-values